fix(dataset):use tf compat for read_file
Using `tf.read_file` on TF2.x would give an `AttributeError` stating that there is no such attribute.
This is because TF2 does not implement this attribute and if we are to use it properly in a TF2 application, we should use the `tf.compat.v1.read_file` instead.